all:
A: A.cpp
	g++ A.cpp -o xA.exe
	./xA.exe < a.in
B: B.cpp
	g++ B.cpp -o xB.exe
	./xB.exe < b.in
C: C.cpp
	g++ C.cpp -o xC.exe
	./xC.exe < c.in
D: D.cpp
	g++ D.cpp -o xD.exe
	./xD.exe < d.in
E: E.cpp
	g++ E.cpp -o xE.exe
	./xE.exe < e.in
F: F.cpp
	g++ F.cpp -o xF.exe
	./xF.exe < f.in
G: G.cpp
	g++ G.cpp -o xG.exe
	./xG.exe < g.in
clean:
	rm *.exe
