all:
A: A.cpp
	g++ A.cpp -o xA.exe
	./xA.exe < a.in
B: B.cpp
	g++ B.cpp -o xB.exe
	./xB.exe < b.in
C1: C1.cpp
	g++ C1.cpp -o xC1.exe
	./xC1.exe < c1.in
C2: C2.cpp
	g++ C2.cpp -o xC2.exe
	./xC2.exe < c2.in
D: D.cpp
	g++ D.cpp -o xD.exe
	./xD.exe < d.in
E: E.cpp
	g++ E.cpp -o xE.exe
	./xE.exe < e.in
F: F.cpp
	g++ F.cpp -o xF.exe
	./xF.exe < f.in
G: G.cpp
	g++ G.cpp -o xG.exe
	./xG.exe < g.in
clean:
	rm *.exe
